name: python27
version: "1.0"
summary: python2.7 snap (ubuntu bionic sources)
description: python2.7
confinement: strict
grade: stable
apps:
  python:
    command: python2.7
    plugs: [network, network-bind]
parts:
  python:
    source: https://git.launchpad.net/~usd-import-team/ubuntu/+source/python2.7
    source-type: git
    source-branch: ubuntu/bionic
    plugin: autotools
    stage:
      - bin
      - lib
      - usr/lib
    configflags:
      - --enable-optimizations
    # apt-get build-dep python2.7
    build-packages:
      - autoconf
      - automake
      - autopoint
      - autotools-dev
      - blt-dev
      - build-essential
      - cpp
      - cpp-7
      - debhelper
      - dh-autoreconf
      - dh-strip-nondeterminism
      - diffstat
      - docutils-common
      - dpkg-dev
      - fontconfig-config
      - fonts-dejavu-core
      - g++
      - g++-7
      - gcc
      - gcc-7
      - gcc-7-base
      - gettext
      - help2man
      - intltool-debian
      - libarchive-zip-perl
      - libasan4
      - libatomic1
      - libbluetooth-dev
      - libbluetooth3
      - libbz2-dev
      - libc-dev-bin
      - libc6-dev
      - libcc1-0
      - libcilkrts5
      - libcroco3
      - libdb-dev
      - libdb5.3-dev
      - libdpkg-perl
      - libdrm-amdgpu1
      - libdrm-intel1
      - libdrm-nouveau2
      - libdrm-radeon1
      - libexpat1-dev
      - libffi-dev
      - libfile-stripnondeterminism-perl
      - libfontconfig1
      - libfontconfig1-dev
      - libfontenc1
      - libfreetype6-dev
      - libgcc-7-dev
      - libgdbm-dev
      - libgl1
      - libgl1-mesa-dri
      - libglapi-mesa
      - libglvnd0
      - libglx-mesa0
      - libglx0
      - libgomp1
      - libice-dev
      - libice6
      - libisl19
      - libitm1
      - libjs-jquery
      - libjs-sphinxdoc
      - libjs-underscore
      - libllvm6.0
      - liblsan0
      - libmpc3
      - libmpx2
      - libncursesw5-dev
      - libpciaccess0
      - libpixman-1-0
      - libpng-dev
      - libpthread-stubs0-dev
      - libpython-stdlib
      - libpython2.7-minimal
      - libpython2.7-stdlib
      - libquadmath0
      - libreadline-dev
      - libsensors4
      - libsm-dev
      - libsm6
      - libsqlite3-dev
      - libssl-dev
      - libstdc++-7-dev
      - libtcl8.6
      - libtimedate-perl
      - libtinfo-dev
      - libtk8.6
      - libtool
      - libtsan0
      - libubsan0
      - libx11-dev
      - libx11-xcb1
      - libxau-dev
      - libxaw7
      - libxcb-dri2-0
      - libxcb-dri3-0
      - libxcb-glx0
      - libxcb-present0
      - libxcb-sync1
      - libxcb1-dev
      - libxdamage1
      - libxdmcp-dev
      - libxext-dev
      - libxfixes3
      - libxfont2
      - libxft-dev
      - libxft2
      - libxkbfile1
      - libxmu6
      - libxpm4
      - libxrender-dev
      - libxrender1
      - libxshmfence1
      - libxss-dev
      - libxss1
      - libxt-dev
      - libxt6
      - libxxf86vm1
      - linux-libc-dev
      - m4
      - make
      - pkg-config
      - po-debconf
      - python
      - python-babel-localedata
      - python-minimal
      - python2.7
      - python2.7-minimal
      - python3-alabaster
      - python3-babel
      - python3-docutils
      - python3-imagesize
      - python3-pygments
      - python3-roman
      - python3-sphinx
      - python3-tz
      - quilt
      - sgml-base
      - sharutils
      - sphinx-common
      - tcl
      - tcl-dev
      - tcl8.6
      - tcl8.6-dev
      - tk
      - tk-dev
      - tk8.6
      - tk8.6-blt2.5
      - tk8.6-dev
      - x11-common
      - x11-xkb-utils
      - x11proto-core-dev
      - x11proto-dev
      - x11proto-scrnsaver-dev
      - x11proto-xext-dev
      - xml-core
      - xorg-sgml-doctools
      - xserver-common
      - xtrans-dev
      - xvfb
      - zlib1g-dev
    stage-packages:
      - libbsd0
      - libbz2-1.0
      - libexpat1
      - libncursesw5
      - libreadline7
      - libtinfo5
      - zlib1g
      - tk8.6-blt2.5
      - libx11-6
      - libxau6
      - libxdmcp6
      - libxext6
      - libxft2
      - libxrender1
      - libxss1
      - libssl1.1
      - libdb5.3
      - libfontconfig1
      - libfreetype6
      - libgdbm5
      - libpng16-16
      - libsqlite3-0
      - libtcl8.6
      - libtk8.6
      - libxcb1
      - libc6
